language: node_js

install:
  - npm install newman

script:
  - node_modules/newman run collections/secondCollection.postman_collection.json -e collections/Testing.postman_environment.json -d collections/testData.json


deploy:
  provider: script
  skip_cleanup: true
  script: bash ciScripts/deploy.sh $TRAVIS_BRANCH
  on: 
    all_branches: true