language: node_js

node_js:
  - "8.2.1"

before_install:
  - npm install -g newman
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - newman -v
  - newman run collections/secondCollection.postman_collection.json -e collections/Testing.postman_environment.json -d collections/testData.json


deploy:
  provider: script
  skip_cleanup: true
  script: bash ciScripts/deploy.sh $TRAVIS_BRANCH
  on: 
    all_branches: true